### ISSUE TITLE
Istio ztunnel installation fails due to ServiceAccount race condition in FluxCD

### ISSUE THREAD

**Issue by marmila** [marmila/picluster#206]
### Issue Description

The istio-ztunnel ServiceAccount exists in the cluster, but Istio specifically expects a ServiceAccount named exactly "ztunnel" (without any prefix). This naming mismatch prevents the ztunnel pods from starting. Additionally, FluxCD reconciliation fails intermittently due to cache-related issues during the installation process.

### RCA

The core issue stems from three interrelated problems:

First, there is a ServiceAccount naming mismatch. While FluxCD automatically creates a ServiceAccount named "istio-ztunnel" (following its naming convention), Istio's ztunnel component strictly requires and looks for a ServiceAccount named simply "ztunnel".

Second, a race condition occurs during pod creation. The ztunnel DaemonSet attempts to create pods before the required ServiceAccount becomes fully available in the Kubernetes API, resulting in creation failures.

Third, FluxCD experiences cache overload. The repeated reconciliation attempts and failures cause the Flux cache to fill up, leading to CacheOperationFailed errors that further compound the problem.

### Technical Impact

This issue specifically affects the deployment of Istio's ztunnel component in ambient mode when managed through FluxCD. The naming requirement is hardcoded in Istio's implementation, while FluxCD follows different naming conventions for generated resources. The cache issues in FluxCD exacerbate the situation by preventing smooth reconciliation retries.

### Environment Details
The problem manifests in environments with:

- k3s version v1.31.4+k3s1
- Istio 1.25.0 or later with ambient mode enabled
- Mixed architecture clusters (ARM/x86)

### Error Manifestation
The primary error appears in cluster events as:
`Error creating: pods 'istio-ztunnel-' is forbidden: error looking up service account istio-system/ztunnel: serviceaccount 'ztunnel' not found`

Simultaneously, FluxCD logs show cache-related errors:
`failed to cache index: Cache is full`

### Fix Applied

1. Created correct SA (Preventing Flux overrides)

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ztunnel
  namespace: istio-system
  annotations:
    fluxcd.io/ignore: "true"  # Hard-lock the SA
    helm.sh/resource-policy: keep  # Block Helm cleanup
EOF
```
2. Patched HelmRelease to Use Pre-Created SA

```
kubectl patch helmrelease istio-ztunnel -n istio-system --type merge --patch '
spec:
  install:
    timeout: 10m  # Extended timeout for ARM nodes
  values:
    serviceAccount:
      create: false  # Disable auto-creation
      name: ztunnel  # Enforce correct name
'
```
3. Forced Flux Reconciliation

`kubectl rollout restart -n flux-system deployment/helm-controller deployment/source-controller`

4. Verification

`watch 'kubectl get pods,sa -n istio-system | grep -E "ztunnel|TARGET"'`
