### ISSUE TITLE
Prometheus PVC size is insufficient for configured retention -- no metrics visible in Grafana

### ISSUE THREAD

**Issue by marmila** [marmila/picluster#257]
Prometheus stopped ingesting metrics due to insufficient persistent storage, which caused Grafana dashboards to stop displaying updated data.

### Problem
In the current configuration (kubernetes/platform/kube-prometheus-stack/app/base/values.yaml):
`retentionSize` is set to 50GB
The persistent volume claim (PVC) is configured with only 10Gi
This mismatch causes Prometheus to quickly fill up the available disk space. Once the disk is full, it stops writing data, resulting in missing metrics in both Prometheus and Grafana.

### Observed Symptoms

- No recent data shown in Grafana
- Prometheus logs include errors such as no space left on device
- `kubectl exec -it prometheus-kube-prometheus-stack-0 -n kube-prom-stack -- df -h /prometheus `  shows 100% disk full
- TSDB stops accepting new time series data

### Proposed Fix
Update the PVC size in the values file to align with the retention settings. Suggested change:

```
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: ${STORAGE_CLASS:=longhorn}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
```
Then commit, reconcuile flux and patch the pvc:
```

kubectl patch pvc prometheus-kube-prometheus-stack-db-prometheus-kube-prometheus-stack-0 \
  -n kube-prom-stack \
  -p '{"spec": {"resources": {"requests": {"storage": "50Gi"}}}}'
```

Alternatively, this value could be made configurable via Helm (e.g. .Values.prometheus.storageSize) to support different environments more flexibly.
